<?php

/**
 * @file
 * Primary module hooks for recetify_content module.
 */

/**
 * Implements hook_preprocess_HOOK().
 */
function recetify_content_preprocess_node(&$variables): void {

  /** @var \Drupal\node\NodeInterface $node */
  $node = $variables['node'];
  $viewMode = $variables['view_mode'];

  if ($node->bundle() === 'home' && $viewMode === 'full') {

    // Preprocess home vars.

  }

}
