_core:
  default_config_hash: dqouFqVseNJNvEjsoYKxbinFOITuCxYhi4y2OTNQP_8
langcode: es
all:
  - language_interface
  - language_content
  - language_url
configurable:
  - language_interface
negotiation:
  language_content:
    enabled:
      language-interface: 0
    method_weights:
      language-url: -20
      language-content-entity: -19
      language-session: -18
      language-user: -17
      language-browser: -16
      language-interface: -15
      language-selected: -14
  language_url:
    enabled:
      language-url: 0
      language-url-fallback: 1
  language_interface:
    enabled:
      language-url: -20
      language-selected: -19
    method_weights:
      language-selected: -19
      language-url: -20
      language-user-admin: -18
      language-session: -17
      language-user: -16
      language-browser: -15
